# Generated by Django 6.0.8 on 2026-08-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='default_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='default_hashtags',
            field=models.TextField(blank=True),
        ),
    ]
